# contraints file (.xdc file) for lab 4
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# UNCOMMENT the below lines to generate a virtual clock required for timing
# analysis
#create_clock -add -name sys_clk_pin -period 12.00 -waveform {0 6} [get_ports
clk]
#set_input_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports
-filter { NAME =~ "*" && DIRECTION == "IN" } ]
#set_output_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports
-filter { NAME =~ "*" && DIRECTION == "OUT" } ]
# leds
#set_property PACKAGE_PIN U16 [get_ports {q[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[0]}]
#set_property PACKAGE_PIN E19 [get_ports {q[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[1]}]
#set_property PACKAGE_PIN U19 [get_ports {q[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[2]}]
#set_property PACKAGE_PIN V19 [get_ports {q[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[3]}]
#set_property PACKAGE_PIN W18 [get_ports {q[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[4]}]
#set_property PACKAGE_PIN U15 [get_ports {q[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[5]}]
#set_property PACKAGE_PIN U14 [get_ports {q[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[6]}]
#set_property PACKAGE_PIN V14 [get_ports {q[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {q[7]}]
set_property PACKAGE_PIN U16 [get_ports {qOut[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[0]}]
set_property PACKAGE_PIN E19 [get_ports {qOut[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[1]}]
set_property PACKAGE_PIN U19 [get_ports {qOut[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[2]}]
set_property PACKAGE_PIN V19 [get_ports {qOut[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[3]}]
set_property PACKAGE_PIN W18 [get_ports {qOut[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[4]}]
set_property PACKAGE_PIN U15 [get_ports {qOut[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[5]}]
set_property PACKAGE_PIN U14 [get_ports {qOut[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[6]}]
set_property PACKAGE_PIN V14 [get_ports {qOut[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {qOut[7]}]
    
set_property PACKAGE_PIN U3 [get_ports {Target[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Target[0]}]
set_property PACKAGE_PIN P3 [get_ports {Target[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Target[1]}]
set_property PACKAGE_PIN N3 [get_ports {Target[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Target[2]}]
set_property PACKAGE_PIN P1 [get_ports {Target[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Target[3]}]
set_property PACKAGE_PIN L1 [get_ports {Target[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Target[4]}]
     
#Buttons
set_property PACKAGE_PIN U18 [get_ports rst]
    set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports roll]
    set_property IOSTANDARD LVCMOS33 [get_ports roll]
# Switches
set_property PACKAGE_PIN V17 [get_ports {seed[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[0]}]
set_property PACKAGE_PIN V16 [get_ports {seed[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[1]}]
set_property PACKAGE_PIN W16 [get_ports {seed[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[2]}]
set_property PACKAGE_PIN W17 [get_ports {seed[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[3]}]
set_property PACKAGE_PIN W15 [get_ports {seed[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[4]}]
set_property PACKAGE_PIN V15 [get_ports {seed[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[5]}]
set_property PACKAGE_PIN W14 [get_ports {seed[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[6]}]
set_property PACKAGE_PIN W13 [get_ports {seed[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seed[7]}]

#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
