# contraints file (.xdc file) for lab 6
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# UNCOMMENT the below lines to generate a virtual clock required for timing
# analysis
#create_clock -add -name sys_clk_pin -period 12.00 -waveform {0 6} [get_ports clk]
#set_input_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports
-filter { NAME =~ "*" && DIRECTION == "IN" } ]
#set_output_delay -clock [get_clocks sys_clk_pin] -add_delay 0.000 [get_ports
-filter { NAME =~ "*" && DIRECTION == "OUT" } ]
# leds
set_property PACKAGE_PIN U16 [get_ports {charCount[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[0]}]
set_property PACKAGE_PIN E19 [get_ports {charCount[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[1]}]
set_property PACKAGE_PIN U19 [get_ports {charCount[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[2]}]
set_property PACKAGE_PIN V19 [get_ports {charCount[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[3]}]
set_property PACKAGE_PIN W18 [get_ports {charCount[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[4]}]
set_property PACKAGE_PIN U15 [get_ports {charCount[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[5]}]
set_property PACKAGE_PIN U14 [get_ports {charCount[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[6]}]
set_property PACKAGE_PIN V14 [get_ports {charCount[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {charCount[7]}]
#set_property PACKAGE_PIN U16 [get_ports {seg[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
#set_property PACKAGE_PIN E19 [get_ports {seg[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
#set_property PACKAGE_PIN U19 [get_ports {seg[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
#set_property PACKAGE_PIN V19 [get_ports {seg[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
#set_property PACKAGE_PIN W18 [get_ports {seg[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
#set_property PACKAGE_PIN U15 [get_ports {seg[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
#set_property PACKAGE_PIN U14 [get_ports {seg[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
#set_property PACKAGE_PIN V14 [get_ports {seg[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
    
     
#Buttons
set_property PACKAGE_PIN U18 [get_ports rst]
    set_property IOSTANDARD LVCMOS33 [get_ports rst]

# Switches
set_property PACKAGE_PIN V17 [get_ports {segIn[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[0]}]
set_property PACKAGE_PIN V16 [get_ports {segIn[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[1]}]
set_property PACKAGE_PIN W16 [get_ports {segIn[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[2]}]
set_property PACKAGE_PIN W17 [get_ports {segIn[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[3]}]
set_property PACKAGE_PIN W15 [get_ports {segIn[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[4]}]
set_property PACKAGE_PIN V15 [get_ports {segIn[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[5]}]
set_property PACKAGE_PIN W14 [get_ports {segIn[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[6]}]
set_property PACKAGE_PIN W13 [get_ports {segIn[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segIn[7]}]
    
set_property PACKAGE_PIN U1 [get_ports {State[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {State[0]}]
set_property PACKAGE_PIN T1 [get_ports {State[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {State[1]}]
set_property PACKAGE_PIN R2 [get_ports {State[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {State[2]}]

#seven-segment LED display
set_property PACKAGE_PIN V7 [get_ports {LED_out[7]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[7]}]
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
